name: Android CI

on:
  push:
  watch:
        types: [started]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build with Gradle
      env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          BDUSS: ${{ secrets.BDUSS }}
          FILE_DIR: download
          FILE_NAME: lou.zip
      run: |
          chmod 777 ./app/post.sh
          ./app/post.sh
